#!/usr/bin/env python


"""FGo! - a simple GUI launcher for FlightGear Flight Simulator."""


from sys import path
from os.path import join

from src import run


SCRIPT_DIR = path[0]
MAIN_DIR = 'src'
WORKING_DIR = join(SCRIPT_DIR, MAIN_DIR)


run(WORKING_DIR)